apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: count-org-loc
  title: count-org-loc
  description: Count total lines of code across a GitHub organization
  annotations:
    github.com/project-slug: ITDeptUtahCountyGovernment/count-org-loc
    backstage.io/source-location: url:https://github.com/ITDeptUtahCountyGovernment/count-org-loc/
    itdept.dev/language: YAML
    itdept.dev/lines-of-code: "132"
    itdept.dev/other-languages: Ruby
    itdept.dev/tech-stack: github-actions
    itdept.dev/correct-naming: "false"
    itdept.dev/password-mgmt: none
    itdept.dev/github-repo: "true"
    itdept.dev/created-at: 2025-03-05T17:02:44Z
    itdept.dev/catalog-last-updated: 2026-09-24T00:42:45.620Z
    itdept.dev/linting-enforced: "false"
    itdept.dev/ci-tested: "false"
    itdept.dev/rad-workflow-adopted: "true"
    itdept.dev/REMOVE-THIS-ANNOTATION: "true"
spec:
  type: config
  owner: group:default/devops-team
  lifecycle: production
